
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../config
patches:
- path: manager_image_patch.yaml
  target:
    group: apps
    kind: Deployment
    name: controller-manager
    version: v1
